// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WormGearKursovaya;

#nullable disable

namespace WormGearKursovaya.Migrations
{
    [DbContext(typeof(DbManager))]
    [Migration("20241202182806_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WormGearKursovaya.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Aw")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CalculationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("D2")
                        .HasColumnType("double precision");

                    b.Property<int>("InputParameterId")
                        .HasColumnType("integer");

                    b.Property<double>("M")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InputParameterId")
                        .IsUnique();

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("WormGearKursovaya.InputParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerN1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q")
                        .HasColumnType("double precision");

                    b.Property<double>("SigmaFP")
                        .HasColumnType("double precision");

                    b.Property<double>("SigmaHP")
                        .HasColumnType("double precision");

                    b.Property<int>("Z1")
                        .HasColumnType("integer");

                    b.Property<int>("Z2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InputParameters");
                });

            modelBuilder.Entity("WormGearKursovaya.Calculation", b =>
                {
                    b.HasOne("WormGearKursovaya.InputParameters", "InputParameter")
                        .WithOne("Calculation")
                        .HasForeignKey("WormGearKursovaya.Calculation", "InputParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputParameter");
                });

            modelBuilder.Entity("WormGearKursovaya.InputParameters", b =>
                {
                    b.Navigation("Calculation");
                });
#pragma warning restore 612, 618
        }
    }
}
